# Generated by Django 5.1.4 on 2025-03-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userrole',
            field=models.CharField(choices=[('BHW', 'Barangay Health Worker'), ('BRGY-STAFF', 'Barangay Staff'), ('DOCTOR', 'Doctor'), ('ADMIN', 'Admin'), ('ROOT', 'Root')], default='BHW', max_length=10),
        ),
    ]
