# Generated by Django 5.1.4 on 2025-02-19 04:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_no', models.AutoField(primary_key=True, serialize=False)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resident',
            name='middle_initial',
        ),
        migrations.AddField(
            model_name='resident',
            name='birthdate',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='resident',
            name='category',
            field=models.CharField(choices=[('NA', 'N/A'), ('Senior', 'Senior'), ('Children', 'Children'), ('Solo Parent', 'Solo Parent'), ('Pregnant', 'Pregnant')], default='NA', max_length=20),
        ),
        migrations.AddField(
            model_name='resident',
            name='civil_status',
            field=models.CharField(default='--', max_length=50),
        ),
        migrations.AddField(
            model_name='resident',
            name='contact_number',
            field=models.CharField(default='--', max_length=20),
        ),
        migrations.AddField(
            model_name='resident',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=20),
        ),
        migrations.AddField(
            model_name='resident',
            name='middle_name',
            field=models.CharField(blank=True, default='--', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='present_address',
            field=models.CharField(default='--', max_length=255),
        ),
        migrations.AddField(
            model_name='resident',
            name='relationship_to_head',
            field=models.CharField(default='--', max_length=50),
        ),
        migrations.AlterField(
            model_name='resident',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resident',
            name='first_name',
            field=models.CharField(default='--', max_length=100),
        ),
        migrations.AlterField(
            model_name='resident',
            name='last_name',
            field=models.CharField(default='--', max_length=100),
        ),
        migrations.AddField(
            model_name='resident',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='residentInfo.family'),
        ),
    ]
