# Generated by Django 5.1.4 on 2025-02-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentInfo', '0002_family_remove_resident_middle_initial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_no',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resident',
            name='category',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Senior', 'Senior'), ('Children', 'Children'), ('Solo Parent', 'Solo Parent'), ('Pregnant', 'Pregnant')], default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='resident',
            name='id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
