# Generated by Django 5.1.4 on 2025-02-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentInfo', '0003_alter_family_family_no_alter_resident_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='category',
            field=models.CharField(choices=[('N/A', 'N/A'), ('PWD', 'PWD'), ('Senior', 'Senior'), ('Children', 'Children'), ('Solo Parent', 'Solo Parent'), ('Pregnant', 'Pregnant')], default='N/A', max_length=20),
        ),
    ]
