# Generated by Django 5.1.4 on 2025-03-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentInfo', '0005_alter_resident_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='category',
            field=models.CharField(choices=[('Adult', 'Adult'), ('PWD', 'PWD'), ('Senior', 'Senior'), ('Children', 'Children'), ('Solo Parent', 'Solo Parent'), ('Pregnant', 'Pregnant')], default='N/A', max_length=20),
        ),
    ]
