# Generated by Django 5.1.4 on 2025-03-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residentInfo', '0002_update_category'),
        ('residentInfo', '0006_alter_resident_category'),
    ]

    operations = [
    ]
