# Generated by Django 5.1.4 on 2025-02-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=100)),
                ('dosage', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('supplier_name', models.CharField(max_length=100)),
                ('unit_price', models.FloatField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
