# Generated by Django 5.1.4 on 2025-02-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicineMonitoring', '0002_remove_medicine_dosage_remove_medicine_expiry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='total_price',
            new_name='total_value',
        ),
    ]
