# Generated by Django 5.1.4 on 2025-02-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicineMonitoring', '0003_rename_total_price_medicine_total_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='total_value',
        ),
        migrations.AddField(
            model_name='medicine',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicine',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
