# Generated by Django 5.1.4 on 2025-02-26 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicineMonitoring', '0004_remove_medicine_total_value_medicine_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='total_price',
            new_name='total_value',
        ),
    ]
