# Generated by Django 5.1.4 on 2025-02-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicineMonitoring', '0005_rename_total_price_medicine_total_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
