# Generated by Django 5.1.4 on 2025-02-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicineMonitoring', '0007_remove_medicinestock_dosage_medicine_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinestock',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
