# Generated by Django 5.1.4 on 2025-02-26 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicineMonitoring', '0008_medicinestock_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinestock',
            old_name='remarks',
            new_name='notes',
        ),
    ]
