# Generated by Django 5.1.4 on 2025-02-28 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicineMonitoring', '0009_rename_remarks_medicinestock_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicinestock',
            options={'ordering': ['expiration_date']},
        ),
        migrations.AddField(
            model_name='medicinestock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='date_last_stock',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicinestock',
            name='expiration_date',
            field=models.DateField(db_index=True),
        ),
    ]
