# Generated by Django 5.1.4 on 2025-02-28 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicineMonitoring', '0010_alter_medicinestock_options_medicinestock_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicinestock',
            options={},
        ),
        migrations.RemoveField(
            model_name='medicinestock',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='date_last_stock',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicinestock',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
