# Generated by Django 5.1.4 on 2025-03-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicineMonitoring', '0012_remove_medicine_total_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='generic_name',
        ),
    ]
