# Generated by Django 5.1.4 on 2025-02-24 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residentInfo', '0004_alter_resident_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visit', models.DateField(blank=True, null=True)),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='residentInfo.resident')),
            ],
        ),
        migrations.CreateModel(
            name='PastMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asthma', models.BooleanField(default=False)),
                ('anemia', models.BooleanField(default=False)),
                ('bad_teeth', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('depression', models.BooleanField(default=False)),
                ('heart_disease', models.BooleanField(default=False)),
                ('hearing_problem', models.BooleanField(default=False)),
                ('high_blood_pressure', models.BooleanField(default=False)),
                ('heart_attack', models.BooleanField(default=False)),
                ('drug_allergy', models.BooleanField(default=False)),
                ('allergy_details', models.TextField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='past_medical_history', to='patientInfo.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PresentIllness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('treatment', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='present_illnesses', to='patientInfo.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hepatitis_a', models.BooleanField(default=False)),
                ('hepatitis_b', models.BooleanField(default=False)),
                ('hpv_vaccine', models.BooleanField(default=False)),
                ('pre_announced_vaccine', models.BooleanField(default=False)),
                ('typhoid', models.BooleanField(default=False)),
                ('mmr', models.BooleanField(default=False)),
                ('dpt', models.BooleanField(default=False)),
                ('chicken_pox', models.BooleanField(default=False)),
                ('tetanus_toxoid', models.BooleanField(default=False)),
                ('others', models.TextField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='patientInfo.patient')),
            ],
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(blank=True, max_length=10, null=True)),
                ('pulse_rate', models.IntegerField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='patientInfo.patient')),
            ],
        ),
    ]
