# Generated by Django 5.1.4 on 2025-02-24 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='last_visit',
        ),
        migrations.AddField(
            model_name='patient',
            name='patientID',
            field=models.CharField(default='P0', editable=False, max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_visited', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patientInfo.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_trackings', to='patientInfo.patient')),
            ],
        ),
    ]
