# Generated by Django 5.1.4 on 2025-03-02 10:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicineMonitoring', '0011_alter_medicinestock_options_and_more'),
        ('patientInfo', '0002_remove_patient_last_visit_patient_patientid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinetracking',
            name='medicine_name',
        ),
        migrations.AddField(
            model_name='medicinetracking',
            name='chief_complain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinetracking',
            name='date_given',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='medicinetracking',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinetracking',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_trackings', to='medicineMonitoring.medicine'),
        ),
        migrations.AddField(
            model_name='medicinetracking',
            name='medicine_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicineMonitoring.medicinestock'),
        ),
        migrations.AddField(
            model_name='medicinetracking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinetracking',
            name='quantity_used',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='medicinetracking',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
