# Generated by Django 5.1.4 on 2025-03-04 12:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientInfo', '0004_rename_dosage_medicinetracking_total_dosage'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinetracking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
