# Generated by Django 5.1.4 on 2025-03-08 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientInfo', '0005_medicinetracking_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentillness',
            name='end_date',
        ),
    ]
