# Generated by Django 5.1.4 on 2025-03-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientInfo', '0006_remove_presentillness_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastmedicalhistory',
            name='others',
            field=models.TextField(blank=True, null=True),
        ),
    ]
