# Generated by Django 5.1.4 on 2025-03-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientInfo', '0008_vitalsignsrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
