# Generated by Django 5.1.4 on 2025-03-19 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientInfo', '0009_medicalrecord_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentillness',
            name='date_visited',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
