# Generated by Django 5.1.4 on 2025-03-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datelog', models.DateField()),
                ('timelog', models.TimeField()),
                ('module', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=20)),
                ('performed_to', models.CharField(max_length=20)),
                ('performed_by', models.CharField(max_length=20)),
            ],
        ),
    ]
